database:
  dsn: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenCons: 114

redis:
  cluster: true  # 启用集群模式
  addrs: # 集群节点地址列表
    - "localhost:6371"  # redis1
    - "localhost:6372"  # redis2
    - "localhost:6373"  # redis3
    - "localhost:6374"  # redis4
  password: ""   # 如果有密码则填写
  pool_size: 10  # 连接池大小